[package]
name = "untitled2"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "untitled2"
path = "src/ti-81_lab_01_var_17_SolomakhaOO.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"